### Updates an existing patient entity
PUT http://localhost:4000/patients/007323dd-1587-456e-bd29-da08238ef206
content-Type: application/json

{
  "name":"update test 4 ",
  "email": "update_test_4@example.com",
  "address": "123 main street",
  "dateOfBirth": "2007-11-28"
}

###