# ===============================
# Application
# ===============================
spring.application.name=patient-service
server.port=4000

# UNCOMMENT TO USE IN MEMORY DATABASE OUTSIDE OF DOCKER
# H2 Database (DEV)
# ===============================
spring.datasource.url=jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin-viewer
spring.datasource.password=password

#h2 is in the pom.xml and good to go but here the h2 string is not described by maven please resolve this issue
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=true
spring.sql.init.mode=always

# DO NOT set dialect manually (auto-detected)
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ===============================
# Logging
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.root=info



